Repository Dr-Pong/dr_pong_game_server, pull requests merged in 2023-09, with the labels that each got.

#77 [Fix] 게임 초대, 큐 입장이 안되는 문제 수정 #76
  src/domain/game/game.service.ts
  src/domain/gateway/game.gateway.ts
  src/domain/gateway/queue.gateway.ts
  src/domain/user/user.service.ts
Labels: fix

#79 [Feat] Jenkins cd add #78
  Jenkinsfile
  deploy/Dockerfile
  deploy/deploy.sh
  docker-compose.yml
Labels: feat

#81 [Feat] githubaction ci add npm test include # 80
  .github/workflows/workflows.yml
Labels: feat

#83 [Fix] 게임 렉 개선하기 #82
  src/domain/factory/model/game.model.ts
  src/domain/factory/objects/ball.ts
  src/domain/factory/objects/bar.ts
  src/domain/game/dto/game.pos.update.dto.ts
  src/domain/game/game.service.ts
  src/domain/gateway/game.gateway.ts
  src/domain/queue/queue.service.ts
  src/domain/user/user.entity.ts
  src/domain/user/user.service.ts
Labels: fix

#86 [Deploy] 배포용 파일 정리 #85
  deploy/Dockerfile
  docker-compose.yml
  nginx/Dockerfile
  nginx/conf/certbot.conf
  nginx/conf/drpong.conf
  nginx/tools/init.sh
  src/main.ts
Labels: feat

#90 [deploy] 배포용 파일 정리 #85
  .github/workflows/workflows.yml
  Dockerfile
  docker-compose.yml
  nginx/Dockerfile
Labels: feat

#98 [Fix] 게임이 여러 개 생성되는 버그 수정 #95
  src/domain/gateway/game.gateway.ts
  src/domain/gateway/queue.gateway.ts
  src/global/utils/socket.utils.ts
Labels: fix

#99 [Refactor] postgres 제거하기 #96
  .github/workflows/workflows.yml
  docker-compose.yml
  src/app.module.ts
  src/app.service.ts
  src/configs/typeorm.config.ts
  src/domain/user/user.module.ts
  src/domain/user/user.service.ts
Labels: refactor
